export interface OSINTTool {
    id: string;
    name: string;
    description: string;
    url: string;
    category: string;
    tags: string[];
}

export const osintTools: OSINTTool[] = [
    // Domain & IP tools
    {
        id: "leakix",
        name: "LeakIX",
        description:
            "Search engine for internet service discovery and vulnerability detection",
        url: "https://leakix.net/",
        category: "domain-ip",
        tags: ["reconnaissance", "vulnerabilities", "leaks"],
    },
    {
        id: "dns-dumpster",
        name: "DNS Dumpster",
        description:
            "DNS reconnaissance tool for mapping network infrastructure",
        url: "https://dnsdumpster.com/",
        category: "domain-ip",
        tags: ["dns", "reconnaissance", "mapping"],
    },
    {
        id: "censys",
        name: "Censys Search",
        description:
            "Internet-wide scanning data for security research and analysis",
        url: "https://search.censys.io/",
        category: "domain-ip",
        tags: ["scanning", "internet", "reconnaissance"],
    },
    {
        id: "rapiddns",
        name: "Rapid DNS",
        description: "Quick DNS lookup tool for domain information gathering",
        url: "https://rapiddns.io/",
        category: "domain-ip",
        tags: ["dns", "lookup", "domain"],
    },
    {
        id: "ssltest",
        name: "SSL Server Test",
        description:
            "Analyze SSL/TLS configurations and identify security vulnerabilities",
        url: "https://www.ssllabs.com/ssltest/",
        category: "domain-ip",
        tags: ["ssl", "security", "analysis"],
    },
    {
        id: "netcraft",
        name: "Netcraft Site Report",
        description: "Detailed analysis of website infrastructure and security",
        url: "https://sitereport.netcraft.com/",
        category: "domain-ip",
        tags: ["infrastructure", "security", "analysis"],
    },

    // Search Engines & Scanning tools
    {
        id: "google-advanced-search",
        name: "Google Advanced Search",
        description: "Advanced search options for precise Google queries.",
        url: "https://www.google.com/advanced_search",
        category: "search-engines",
        tags: ["google", "search", "advanced"],
    },
    {
        id: "shodan",
        name: "Shodan",
        description: "Search engine for internet-connected devices and vulnerabilities.",
        url: "https://www.shodan.io/",
        category: "search-engines",
        tags: ["devices", "vulnerabilities", "search"],
    },
    {
        id: "crt-sh",
        name: "crt.sh",
        description: "Search engine for SSL/TLS certificates.",
        url: "https://crt.sh/",
        category: "search-engines",
        tags: ["certificates", "ssl", "tls"],
    },
    {
        id: "yandex",
        name: "Yandex",
        description: "Russian search engine with global reach.",
        url: "https://yandex.com/",
        category: "search-engines",
        tags: ["search", "global", "yandex"],
    },
    {
        id: "bing",
        name: "Bing",
        description: "Microsoft's search engine for web queries.",
        url: "https://www.bing.com/",
        category: "search-engines",
        tags: ["search", "microsoft", "web"],
    },
    {
        id: "duckduckgo",
        name: "Duck Duck Go",
        description: "Privacy-focused search engine with no tracking.",
        url: "https://duckduckgo.com/",
        category: "search-engines",
        tags: ["privacy", "search", "no-tracking"],
    },
    {
        id: "google-hacking-database",
        name: "Google Hacking DataBase",
        description: "Collection of Google search queries for finding sensitive information.",
        url: "https://www.exploit-db.com/google-hacking-database",
        category: "search-engines",
        tags: ["google", "hacking", "database"],
    },
    {
        id: "virus-total",
        name: "Virus Total",
        description: "Multi-engine malware and URL scanning service.",
        url: "https://www.virustotal.com/gui/home/upload",
        category: "search-engines",
        tags: ["malware", "scanning", "security"],
    },
    {
        id: "malicious-link-check",
        name: "DFNDR Lab Link Check",
        description: "Tool to verify if links are safe or malicious",
        url: "https://www.psafe.com/dfndr-lab/",
        category: "search-engines",
        tags: ["url", "security", "verification"],
    },
    {
        id: "web-check",
        name: "Web Check",
        description:
            "Comprehensive website analysis and information gathering tool",
        url: "https://web-check.as93.net/",
        category: "search-engines",
        tags: ["analysis", "information", "reconnaissance"],
    },

    // Email tools
    {
        id: "check-short-url",
        name: "Check Short URL",
        description:
            "Reveal the destination of shortened URLs before visiting them",
        url: "https://checkshorturl.com/",
        category: "email",
        tags: ["url", "shortener", "security"],
    },
    {
        id: "url-redirect-checker",
        name: "URL Redirect Checker",
        description:
            "Track all redirects from the original URL to the final destination",
        url: "https://wheregoes.com/",
        category: "email",
        tags: ["redirect", "tracking", "url"],
    },
    {
        id: "wayback-machine",
        name: "Internet Archive Wayback Machine",
        description:
            "Access historical versions of websites and deleted content",
        url: "https://web.archive.org/",
        category: "email",
        tags: ["archive", "history", "deleted content"],
    },
    {
        id: "inteltechniques-domains",
        name: "IntelTechniques: Domains Search Tool",
        description: "Comprehensive domain intelligence and search utilities",
        url: "https://inteltechniques.com/tools/Domain.html",
        category: "email",
        tags: ["domain", "intelligence", "search"],
    },
    {
        id: "blackbird",
        name: "Blackbird",
        description:
            "Check usernames and email addresses across websites and networks",
        url: "https://github.com/p1ngul1n0/blackbird",
        category: "email",
        tags: ["username", "email", "verification", "multi-platform"],
    },
    {
        id: "have-i-been-pwned",
        name: "Have I Been Pwned?",
        description: "Check if email or phone number appears in data breaches.",
        url: "https://haveibeenpwned.com/",
        category: "email",
        tags: ["email", "breach", "security", "phone"],
    },
    {
        id: "epieos",
        name: "Epieos",
        description: "Tool for searching email addresses and related data.",
        url: "https://epieos.com/",
        category: "email",
        tags: ["email", "search", "data"],
    },
    {
        id: "hunter-io",
        name: "Hunter.io",
        description: "Tool for finding email addresses and verifying domains.",
        url: "https://hunter.io/",
        category: "email",
        tags: ["email", "verification", "domains"],
    },
    {
        id: "whats-my-name",
        name: "Whats My Name",
        description: "Tool to find usernames across social media platforms.",
        url: "https://whatsmyname.app/",
        category: "email",
        tags: ["usernames", "social-media", "search"],
    },
    {
        id: "intelx-email",
        name: "Intelligence X Email",
        description: "Search engine for leaked data and email intelligence.",
        url: "https://intelx.io/tools?tab=email",
        category: "email",
        tags: ["email", "leaks", "intelligence"],
    },
    {
        id: "proofy",
        name: "Proofy.io",
        description: "Email verification and validation tool.",
        url: "https://proofy.io/",
        category: "email",
        tags: ["email", "verification", "validation"],
    },
    {
        id: "predicta-search",
        name: "Predicta Search",
        description: "Tool for email and contact intelligence.",
        url: "https://www.predictasearch.com/",
        category: "email",
        tags: ["email", "contact", "intelligence"],
    },
    {
        id: "get-prospect",
        name: "Get Prospect",
        description: "Tool for finding and managing email leads.",
        url: "https://getprospect.com/",
        category: "email",
        tags: ["email", "leads", "management"],
    },
    {
        id: "anymail-finder",
        name: "Anymail Finder",
        description: "Tool for finding and verifying email addresses.",
        url: "https://anymailfinder.com/",
        category: "email",
        tags: ["email", "finder", "verification"],
    },

    // Communication tools
    {
        id: "disboard",
        name: "Disboard",
        description:
            "Search engine for public Discord servers by category and keywords",
        url: "https://disboard.org/servers",
        category: "communication",
        tags: ["discord", "servers", "search", "communities"],
    },
    {
        id: "discord-leaks",
        name: "DiscordLeaks",
        description:
            "Search database of leaked messages from extremist Discord servers",
        url: "https://discordleaks.unicornriot.ninja/discord/server/",
        category: "communication",
        tags: ["discord", "leaks", "extremism", "investigation"],
    },
    {
        id: "intelx-telegram",
        name: "Intelligence X Telegram Search",
        description: "Search engine for Telegram content",
        url: "https://intelx.io/tools?tab=telegram",
        category: "communication",
        tags: ["telegram", "search", "intelligence"],
    },
    {
        id: "telegago",
        name: "Telegago",
        description: "Google Custom Search Engine for public Telegram content",
        url: "http://bit.ly/telegago",
        category: "communication",
        tags: ["telegram", "search", "google-cse"],
    },
    {
        id: "telegram-group-joiner",
        name: "Telegram Group Joiner",
        description:
            "Tool to automate joining multiple Telegram groups and channels",
        url: "https://bellingcat.github.io/telegram-group-joiner/",
        category: "communication",
        tags: ["telegram", "automation", "research", "bellingcat"],
    },
    {
        id: "telegram-phone-checker",
        name: "Telegram Phone Number Checker",
        description:
            "Check if phone numbers are connected to Telegram accounts",
        url: "https://colab.research.google.com/github/bellingcat/open-source-research-notebooks/blob/main/notebooks/bellingcat/telegram-phone-number-checker.ipynb",
        category: "communication",
        tags: ["telegram", "phone", "verification", "colab"],
    },
    {
        id: "telegramdb",
        name: "TelegramDB",
        description:
            "Searchable database of public Telegram groups and channels",
        url: "https://telegramdb.org",
        category: "communication",
        tags: ["telegram", "database", "search", "groups"],
    },
    {
        id: "telemetrio",
        name: "Telemetrio",
        description: "Analytics and catalog of Telegram channels with rankings",
        url: "https://telemetr.io/",
        category: "communication",
        tags: ["telegram", "analytics", "rankings", "channels"],
    },
    {
        id: "telepathy",
        name: "Telepathy",
        description: "Versatile Telegram toolkit for OSINT analysis",
        url: "https://github.com/jordanwildon/Telepathy",
        category: "communication",
        tags: ["telegram", "osint", "analysis", "github"],
    },
    {
        id: "tgstat",
        name: "TGStat",
        description:
            "Analytics tool for monitoring Telegram channels and statistics",
        url: "https://tgstat.com/",
        category: "communication",
        tags: ["telegram", "analytics", "statistics", "monitoring"],
    },
    {
        id: "tlgrm-channels",
        name: "tlgrm.eu channels",
        description: "Search engine for Telegram channels",
        url: "http://tlgrm.eu/channels",
        category: "communication",
        tags: ["telegram", "search", "channels"],
    },
    {
        id: "watools",
        name: "WAtools.io",
        description:
            "Track WhatsApp activity, verify numbers, and view profile pictures",
        url: "http://watools.io/",
        category: "communication",
        tags: ["whatsapp", "activity", "profile", "verification"],
    },

    // Social Media tools
    {
        id: "facebook-live-map",
        name: "Facebook Live Map",
        description: "Interactive map showing live broadcasts around the world",
        url: "http://facebook.com/livemap",
        category: "social-media",
        tags: ["facebook", "livestream", "map", "geolocation"],
    },
    {
        id: "facebook-video-downloader",
        name: "Facebook Video Downloader",
        description:
            "Download public Facebook videos in various quality formats",
        url: "http://fdown.net/",
        category: "social-media",
        tags: ["facebook", "video", "download", "media"],
    },
    {
        id: "haveibeenzuckered",
        name: "HaveIBeenZuckered",
        description:
            "Check if a phone number appears in Facebook data breaches",
        url: "https://haveibeenzuckered.com/",
        category: "social-media",
        tags: ["facebook", "breach", "phone", "security"],
    },
    {
        id: "sowdust-fb-search",
        name: "Sowdust Facebook Search",
        description:
            "Advanced interface for Facebook search after Graph Search shutdown",
        url: "http://sowsearch.info",
        category: "social-media",
        tags: ["facebook", "search", "advanced", "graph"],
    },
    {
        id: "who-posted-what",
        name: "Who Posted What?",
        description:
            "Search Facebook content by keyword within specific time frames",
        url: "https://whopostedwhat.com/",
        category: "social-media",
        tags: ["facebook", "search", "timestamp", "history"],
    },
    {
        id: "bellingcat-insta-location",
        name: "Bellingcat Instagram Location Search",
        description: "Find Instagram location IDs near specified coordinates",
        url: "https://github.com/bellingcat/instagram-location-search",
        category: "social-media",
        tags: ["instagram", "location", "geolocation", "coordinates"],
    },
    {
        id: "instaloader",
        name: "InstaLoader",
        description:
            "Download Instagram pictures, videos, captions and metadata",
        url: "https://instaloader.github.io",
        category: "social-media",
        tags: ["instagram", "download", "scraper", "metadata"],
    },
    {
        id: "picuki",
        name: "Picuki",
        description: "View and download Instagram content without login",
        url: "https://www.picuki.com/",
        category: "social-media",
        tags: ["instagram", "viewer", "anonymous", "download"],
    },
    {
        id: "story-saver",
        name: "Story Saver",
        description: "Download public Instagram Stories, Highlights and Videos",
        url: "https://storysaver.net",
        category: "social-media",
        tags: ["instagram", "stories", "highlights", "download"],
    },
    {
        id: "email-to-linkedin",
        name: "Email to LinkedIn (Epieos)",
        description:
            "Check if an email address is connected to a LinkedIn Profile",
        url: "https://tools.epieos.com/linkedin.php",
        category: "social-media",
        tags: ["linkedin", "email", "verification", "connection"],
    },
    {
        id: "linkedin-overlay-remover",
        name: "LinkedIn Overlay Remover",
        description: "Firefox addon to remove the overlay on LinkedIn profiles",
        url: "http://addons.mozilla.org/nl/firefox/addon/linkedin-overlay-remover/",
        category: "social-media",
        tags: ["linkedin", "addon", "overlay", "firefox"],
    },
    {
        id: "namechk",
        name: "Namechk",
        description: "Check username availability across platforms and domains",
        url: "https://namechk.com/",
        category: "social-media",
        tags: ["username", "domain", "availability"],
    },
    {
        id: "open-measures",
        name: "Open Measures",
        description: "Tools for investigating harmful online activity",
        url: "https://openmeasures.io/",
        category: "social-media",
        tags: ["investigation", "extremism", "disinformation", "analysis"],
    },
    {
        id: "sherlock",
        name: "Sherlock",
        description:
            "Hunt down social media accounts by username across 400+ sites",
        url: "https://github.com/sherlock-project/sherlock",
        category: "social-media",
        tags: ["username", "search", "multi-platform", "github"],
    },
    {
        id: "whatsmyname",
        name: "WhatsMyName",
        description: "Username search tool for hundreds of platforms",
        url: "https://whatsmyname.app/",
        category: "social-media",
        tags: ["username", "search", "multi-platform"],
    },
    {
        id: "bellingcat-tiktok-timestamp",
        name: "Bellingcat TikTok Date Extract",
        description: "Get exact upload date and time for TikTok videos",
        url: "https://bellingcat.github.io/tiktok-timestamp",
        category: "social-media",
        tags: ["tiktok", "timestamp", "metadata", "bellingcat"],
    },
    {
        id: "bellingcat-tiktok-hashtag",
        name: "Bellingcat TikTok Hashtag Analysis",
        description: "Archive content and metadata from TikTok hashtags",
        url: "https://github.com/bellingcat/tiktok-hashtag-analysis",
        category: "social-media",
        tags: ["tiktok", "hashtag", "archive", "analysis"],
    },
    {
        id: "tiktok-api",
        name: "TikTokApi",
        description: "Unofficial Python API wrapper for TikTok",
        url: "https://pypi.org/project/TikTokApi",
        category: "social-media",
        tags: ["tiktok", "api", "python", "scraping"],
    },
    {
        id: "hoaxy",
        name: "Hoaxy",
        description:
            "Visualize the spread of information on Bluesky and X/Twitter",
        url: "https://hoaxy.osome.iu.edu/",
        category: "social-media",
        tags: ["twitter", "bluesky", "visualization", "information-spread"],
    },
    {
        id: "twitter-location-search",
        name: "Twitter/X Location Search",
        description: "Search for geocoded tweets near specified coordinates",
        url: "https://twitter.com/explore",
        category: "social-media",
        tags: ["twitter", "location", "geocoded", "coordinates"],
    },
    {
        id: "twitter-video-downloader",
        name: "Twitter Video Downloader",
        description: "Download videos from Twitter/X posts",
        url: "https://twittervideodownloader.com/",
        category: "social-media",
        tags: ["twitter", "video", "download", "media"],
    },
    {
        id: "bellingcat-vk-scraper",
        name: "Bellingcat VK Scraper",
        description: "Scrape data and media from VK.com URLs",
        url: "https://github.com/bellingcat/vk-url-scraper",
        category: "social-media",
        tags: ["vk", "scraper", "media", "bellingcat"],
    },
    {
        id: "vk-watch",
        name: "VK.watch",
        description: "View public comments and profile photos from VK accounts",
        url: "http://vk.watch/",
        category: "social-media",
        tags: ["vk", "comments", "photos", "monitoring"],
    },
    {
        id: "f5bot",
        name: "F5Bot",
        description: "Email alerts when keywords are mentioned on Reddit",
        url: "https://f5bot.com/",
        category: "social-media",
        tags: ["reddit", "keywords", "monitoring", "alerts"],
    },
    {
        id: "redective",
        name: "Redective",
        description:
            "Reddit profile analysis tool with word frequency and active hours",
        url: "https://www.redective.com/",
        category: "social-media",
        tags: ["reddit", "analysis", "profiles", "activity"],
    },
    {
        id: "clubhousedb",
        name: "ClubhouseDB",
        description:
            "Search Clubhouse users by followers/following and registration date",
        url: "https://clubhousedb.com/",
        category: "social-media",
        tags: ["clubhouse", "users", "search", "database"],
    },
    {
        id: "namemc",
        name: "NameMC",
        description: "Track Minecraft usernames and username changes",
        url: "https://namemc.com/",
        category: "social-media",
        tags: ["minecraft", "username", "history", "gaming"],
    },
    {
        id: "psnprofiles",
        name: "PSNprofiles",
        description: "Search PlayStation usernames and view gaming activity",
        url: "https://psnprofiles.com/",
        category: "social-media",
        tags: ["playstation", "gaming", "profiles", "activity"],
    },
    {
        id: "steamid",
        name: "SteamId.uk",
        description: "Lookup Steam player info and friendship connections",
        url: "http://steamid.uk/",
        category: "social-media",
        tags: ["steam", "gaming", "profiles", "connections"],
    },
    {
        id: "xbox-gamertag",
        name: "XboxGamertag",
        description: "Search Xbox gamertags and view game activity",
        url: "https://xboxgamertag.com/",
        category: "social-media",
        tags: ["xbox", "gaming", "profiles", "activity"],
    },

    // Images & Media tools
    {
        id: "findclone",
        name: "FindClone",
        description: "Facial recognition search for VK profile images",
        url: "https://findclone.ru/",
        category: "images-media",
        tags: ["vk", "facial-recognition", "search", "images"],
    },
    {
        id: "search4faces",
        name: "Search4Faces",
        description:
            "Facial recognition search across VK, Odnoklassniki, TikTok, and Clubhouse",
        url: "https://search4faces.com",
        category: "images-media",
        tags: ["facial-recognition", "search", "images", "multi-platform"],
    },
    {
        id: "youtube-dl",
        name: "youtube-dl",
        description:
            "Command line tool to download videos from YouTube and other sites",
        url: "http://rg3.github.io/youtube-dl/",
        category: "images-media",
        tags: ["youtube", "download", "video", "command-line"],
    },
    {
        id: "youtube-metadata",
        name: "YouTube Metadata",
        description: "Tool to extract and analyze metadata from YouTube videos",
        url: "https://mattw.io/youtube-metadata/",
        category: "images-media",
        tags: ["youtube", "metadata", "analysis", "investigation"],
    },
    {
        id: "google-lens",
        name: "Google Lens",
        description: "Image recognition and search tool by Google.",
        url: "https://lens.google/",
        category: "images-media",
        tags: ["image", "recognition", "search"],
    },
    {
        id: "sun-calc",
        name: "Sun Calc",
        description: "Tool to calculate sun position and sunlight phases.",
        url: "https://www.suncalc.org/",
        category: "images-media",
        tags: ["sun", "position", "calculation"],
    },
    {
        id: "invid-project",
        name: "InVID Project",
        description: "Tool for video verification and analysis.",
        url: "https://www.invid-project.eu/",
        category: "images-media",
        tags: ["video", "verification", "analysis"],
    },
    {
        id: "photo-forensics",
        name: "Photo Forensics",
        description: "Tool for analyzing and verifying photo authenticity.",
        url: "https://29a.ch/photo-forensics/#forensic-magnifier",
        category: "images-media",
        tags: ["photo", "forensics", "authenticity"],
    },
    {
        id: "pim-eye",
        name: "Pim Eye",
        description: "Facial recognition and reverse image search tool.",
        url: "https://pimeyes.com/en",
        category: "images-media",
        tags: ["facial-recognition", "reverse-image", "search"],
    },
    {
        id: "rootabout",
        name: "RootAbout",
        description: "Tool for image and video analysis.",
        url: "https://rootabout.com/",
        category: "images-media",
        tags: ["image", "video", "analysis"],
    },
    {
        id: "tin-eye",
        name: "Tin Eye",
        description: "Reverse image search engine.",
        url: "https://tineye.com/",
        category: "images-media",
        tags: ["reverse-image", "search", "engine"],
    },
    {
        id: "jimple-exif",
        name: "Jimple Exif Data",
        description: "Tool to extract EXIF data from images.",
        url: "https://jimpl.com/",
        category: "images-media",
        tags: ["exif", "data", "images"],
    },
    {
        id: "geo-spy",
        name: "Geo Spy",
        description: "Tool for geolocation and image analysis.",
        url: "https://geospy.ai/",
        category: "images-media",
        tags: ["geolocation", "image", "analysis"],
    },
    {
        id: "yandex-image-search",
        name: "Yandex Image Search",
        description: "Reverse image search engine by Yandex.",
        url: "https://yandex.com/images/",
        category: "images-media",
        tags: ["reverse-image", "search", "yandex"],
    },
    {
        id: "meta-data",
        name: "Meta Data",
        description: "Tool to extract metadata from files and images.",
        url: "https://www.metadata2go.com/",
        category: "images-media",
        tags: ["metadata", "files", "images"],
    },
    {
        id: "my-heritage-photo-enhancer",
        name: "My Heritage Photo Enhancer",
        description: "Tool to enhance and restore old photos.",
        url: "https://www.myheritage.nl/photo-enhancer",
        category: "images-media",
        tags: ["photo", "enhancer", "restoration"],
    },
    {
        id: "clipdrop-cleanup",
        name: "ClipDrop Cleanup",
        description: "Tool to clean up images and remove unwanted objects.",
        url: "https://clipdrop.co/cleanup",
        category: "images-media",
        tags: ["image", "cleanup", "objects"],
    },

    // Geolocation tools
    {
        id: "google-maps",
        name: "Google Maps",
        description: "Comprehensive mapping service by Google.",
        url: "https://www.google.com/maps",
        category: "geolocation",
        tags: ["maps", "google", "navigation"],
    },
    {
        id: "bing-maps",
        name: "Bing Maps",
        description: "Microsoft's mapping and navigation platform.",
        url: "https://www.bing.com/maps",
        category: "geolocation",
        tags: ["maps", "bing", "navigation"],
    },
    {
        id: "yandex-maps",
        name: "Yandex Maps",
        description: "Mapping service by Yandex with global coverage.",
        url: "https://yandex.com/maps/",
        category: "geolocation",
        tags: ["maps", "yandex", "navigation"],
    },
    {
        id: "baidu-maps",
        name: "Baidu Maps",
        description: "Chinese mapping service with extensive local data.",
        url: "https://map.baidu.com/",
        category: "geolocation",
        tags: ["maps", "baidu", "china"],
    },
    {
        id: "suncalc",
        name: "SunCalc",
        description: "Tool to calculate sun position and sunlight phases.",
        url: "https://www.suncalc.org/",
        category: "geolocation",
        tags: ["sun", "position", "calculation"],
    },
    {
        id: "liveuamap",
        name: "Liveuamap",
        description: "Live mapping of conflicts and global events.",
        url: "https://liveuamap.com/",
        category: "geolocation",
        tags: ["live", "events", "conflicts"],
    },
    {
        id: "satellites-pro",
        name: "Satellites Pro",
        description: "Satellite imagery and mapping platform.",
        url: "https://satellites.pro/",
        category: "geolocation",
        tags: ["satellite", "imagery", "maps"],
    },
    {
        id: "mapillary",
        name: "Mapillary",
        description: "Crowdsourced street-level imagery platform.",
        url: "https://www.mapillary.com/app/",
        category: "geolocation",
        tags: ["street", "imagery", "crowdsourced"],
    },
    {
        id: "nasa-firms",
        name: "NASA FIRMS",
        description: "Fire Information for Resource Management System by NASA.",
        url: "https://firms.modaps.eosdis.nasa.gov/map/",
        category: "geolocation",
        tags: ["nasa", "fire", "management"],
    },
    {
        id: "google-earth",
        name: "Google Earth",
        description: "3D representation of Earth based on satellite imagery.",
        url: "https://earth.google.com/web/",
        category: "geolocation",
        tags: ["earth", "3d", "satellite"],
    },
    {
        id: "flightradar24",
        name: "Flightradar24",
        description: "Live flight tracking platform.",
        url: "https://www.flightradar24.com/",
        category: "geolocation",
        tags: ["flight", "tracking", "live"],
    },
    {
        id: "marinetraffic",
        name: "MarineTraffic",
        description: "Live tracking of ships and maritime traffic.",
        url: "https://www.marinetraffic.com/en/ais/home/",
        category: "geolocation",
        tags: ["ships", "tracking", "maritime"],
    },
    {
        id: "zoom-earth",
        name: "Zoom Earth",
        description: "Satellite and weather imagery in real-time.",
        url: "https://zoom.earth/maps/satellite/",
        category: "geolocation",
        tags: ["satellite", "weather", "real-time"],
    },
    {
        id: "gps-jamming",
        name: "GPS Jamming",
        description: "Live map of GPS jamming incidents.",
        url: "https://www.flightradar24.com/data/gps-jamming",
        category: "geolocation",
        tags: ["gps", "jamming", "live"],
    },

    // Darkweb tools (placeholder - you can add actual darkweb tools here)
    {
        id: "darkweb-search",
        name: "Dark Web Search",
        description: "Search engine for dark web content and hidden services",
        url: "#",
        category: "darkweb",
        tags: ["darkweb", "search", "hidden-services"],
    },
    {
        id: "tor-search",
        name: "Tor Search",
        description: "Search engine for Tor hidden services and dark web sites",
        url: "#",
        category: "darkweb",
        tags: ["tor", "darkweb", "hidden-services"],
    },

    // Satellite OSINT tools
    {
        id: "find-satellites",
        name: "Find Satellites",
        description: "Track current satellites location across the globe.",
        url: "https://www.find-satellites.com/",
        category: "satellite",
        tags: ["satellite", "imagery", "earth observation", "analysis"],
    },
    {
        id: "eo-browser",
        name: "EO Browser",
        description:
            "Browse and visualize satellite data from multiple sources.",
        url: "https://apps.sentinel-hub.com/eo-browser/",
        category: "satellite",
        tags: ["satellite", "visualization", "earth observation"],
    },
    {
        id: "google-earth-engine",
        name: "Google Earth Engine",
        description:
            "Cloud-based platform for planetary-scale geospatial analysis.",
        url: "https://earthengine.google.com/",
        category: "satellite",
        tags: ["satellite", "geospatial", "analysis", "google"],
    },
    {
        id: "zoom-earth",
        name: "Zoom Earth",
        description: "Live satellite images and weather maps.",
        url: "https://zoom.earth/",
        category: "satellite",
        tags: ["satellite", "weather", "live imagery"],
    },
    {
        id: "nasa-worldview",
        name: "NASA Worldview",
        description:
            "Interactively browse global, full-resolution satellite imagery.",
        url: "https://worldview.earthdata.nasa.gov/",
        category: "satellite",
        tags: ["satellite", "nasa", "imagery", "global"],
    },
    {
        id: "soar-earth",
        name: "Soar.Earth",
        description:
            "Access and share high-resolution drone and satellite maps.",
        url: "https://soar.earth/",
        category: "satellite",
        tags: ["satellite", "drone", "maps", "sharing"],
    },
    {
        id: "terraserver",
        name: "Terraserver",
        description: "Satellite and aerial imagery for the United States.",
        url: "https://www.terraserver.com/",
        category: "satellite",
        tags: ["satellite", "aerial", "us", "imagery"],
    },
    {
        id: "usgs-earth-explorer",
        name: "USGS Earth Explorer",
        description:
            "Search and download satellite images, aerial photographs, and cartographic products.",
        url: "https://earthexplorer.usgs.gov/",
        category: "satellite",
        tags: ["satellite", "usgs", "download", "imagery"],
    },
    {
        id: "copernicus-open-access-hub",
        name: "Copernicus Open Access Hub",
        description:
            "Access Sentinel satellite data from the Copernicus program.",
        url: "https://scihub.copernicus.eu/",
        category: "satellite",
        tags: ["satellite", "copernicus", "sentinel", "data"],
    },
    {
        id: "skywatch",
        name: "SkyWatch",
        description: "Platform for discovering and ordering satellite imagery.",
        url: "https://skywatch.com/",
        category: "satellite",
        tags: ["satellite", "imagery", "platform"],
    },
    {
        id: "satnogs",
        name: "SatNOGS",
        description: "Open satellite ground-station network and database.",
        url: "https://network.satnogs.org/",
        category: "satellite",
        tags: ["satellite", "ground-station", "network"],
    },
    {
        id: "heavens-above",
        name: "Heavens Above",
        description: "Track satellites, ISS, and other objects in the sky.",
        url: "https://heavens-above.com/",
        category: "satellite",
        tags: ["satellite", "tracking", "iss", "sky"],
    },
    {
        id: "n2yo",
        name: "N2YO",
        description: "Real-time satellite tracking and predictions.",
        url: "https://www.n2yo.com/",
        category: "satellite",
        tags: ["satellite", "tracking", "real-time"],
    },
    {
        id: "calsky",
        name: "Calsky",
        description: "Astronomical calculations and satellite tracking.",
        url: "https://www.calsky.com/",
        category: "satellite",
        tags: ["satellite", "astronomy", "tracking"],
    },
    {
        id: "in-the-sky",
        name: "In-The-Sky.org",
        description:
            "Astronomy and satellite events, tracking, and predictions.",
        url: "https://in-the-sky.org/",
        category: "satellite",
        tags: ["satellite", "astronomy", "events", "tracking"],
    },
// AI Tools
  {
    "id": "dork-gpt",
    "name": "Dork GPT",
    "description": "An AI-powered tool for generating advanced search queries (Google dorks) for security and research purposes.",
    "url": "https://www.dorkgpt.com/",
    "category": "ai-tools",
    "tags": ["ai", "security", "dorking", "search", "research"]
  },
  {
    "id": "chatgpt",
    "name": "ChatGPT",
    "description":
      "A large language model-based chatbot developed by OpenAI for conversational AI, text generation, and more.",
    "url": "https://chatgpt.com/",
    "category": "ai-tools",
    "tags": ["ai", "chatbot", "openai", "llm", "conversational-ai"]
  },
  {
    "id": "gemini",
    "name": "Gemini",
    "description":
      "A family of multimodal large language models by Google, capable of understanding text, images, audio, and video.",
    "url": "https://gemini.google.com/app",
    "category": "ai-tools",
    "tags": ["ai", "chatbot", "google", "llm", "multimodal"]
  },
  {
    "id": "deepseek",
    "name": "DeepSeek",
    "description":
      "An AI chat tool with a strong focus on coding and reasoning abilities, developed by DeepSeek AI.",
    "url": "https://chat.deepseek.com/",
    "category": "ai-tools",
    "tags": ["ai", "chatbot", "coding", "llm", "developer-tool"]
  },
  {
    "id": "kali-gpt",
    "name": "Kali GPT",
    "description":
      "A custom GPT model on the ChatGPT platform designed to assist with cybersecurity tasks related to the Kali Linux distribution.",
    "url": "https://chatgpt.com/g/g-uRhIB5ire-kali-gpt",
    "category": "ai-tools",
    "tags": ["ai", "gpt", "cybersecurity", "kali-linux", "pentesting"]
  },
  {
    "id": "perplexity-ai",
    "name": "Perplexity AI",
    "description":
      "An AI-powered conversational search engine that provides direct answers to questions with cited sources from the web.",
    "url": "https://www.perplexity.ai/",
    "category": "ai-tools",
    "tags": ["ai", "search-engine", "research", "citations"]
  },
  {
    "id": "claude",
    "name": "Claude",
    "description":
      "An AI assistant developed by Anthropic, focused on helpful, harmless, and honest conversations.",
    "url": "https://claude.ai/new",
    "category": "ai-tools",
    "tags": ["ai", "chatbot", "anthropic", "llm", "conversational-ai"]
  }

];

export const getToolsByCategory = (category: string): OSINTTool[] => {
    return osintTools.filter((tool) => tool.category === category);
};

export const getCategoryTools = () => {
    const categories = {
        "search-engines": getToolsByCategory("search-engines"),
        "social-media": getToolsByCategory("social-media"),
        "domain-ip": getToolsByCategory("domain-ip"),
        "images-media": getToolsByCategory("images-media"),
        geolocation: getToolsByCategory("geolocation"),
        darkweb: getToolsByCategory("darkweb"),
        communication: getToolsByCategory("communication"),
        email: getToolsByCategory("email"),
        satellite: getToolsByCategory("satellite"),
        "ai-tools": getToolsByCategory("ai-tools"),
    };
    return categories;
};
